### ISSUE TITLE
Jest cannot resolve imports on fresh workspace (12.5.0)

### ISSUE THREAD

**Issue by guiccbr** [nrwl/nx-react-native#92]
Hey everyone, hello.

I was having a problem after migrating to 12.5.0, where Jest tests would not pass if the tested component imported libs from other directories. I thought that it could be something with my workspace so I started a new one from scratch, but I'm still seeing the same problem.

These are the steps to reproduce:

```
- npx create-nx-workspace@12.5.0 (used 12.5.0 on this example, but the same thing happens on latest)
- yarn add -D @nwrl/react-native
- yarn nx g @nrwl/react-native:app ReactNativeApp
- yarn nx g @nrwl/react-native:lib my-library
```

Then I just went to my-library and created a simple View and imported it into `App.tsx`. If I run the app, I can see the view on the simulator, everything works fine. But if I try to run `yarn nx test react-native-app`, I'm getting this error:

```
$ nx test react-native-app

> nx run react-native-app:test
 FAIL   react-native-app  apps/react-native-app/src/app/App.spec.tsx
  ● Test suite failed to run

    Cannot find module '@my-workspace3/my-library' from 'src/app/App.tsx'

    Require stack:
      src/app/App.tsx
      src/app/App.spec.tsx

      18 | // @ts-ignore
      19 | import openURLInBrowser from 'react-native/Libraries/Core/Devtools/openURLInBrowser';
    > 20 | import { MyLibrary } from '@my-workspace3/my-library';
         |                  ^
      21 |
      22 | const App = () => {
      23 |   return (

      at Resolver.resolveModule (../../node_modules/jest-resolve/build/resolver.js:311:11)
      at Object.<anonymous> (src/app/App.tsx:20:18)
```

Does anyone know what's going on? I've been struggling with this for some time already, but didn't find a solution. It would be awesome if someone could help with some insights. Thanks!

**Comment by xiongemi** [comment]
add `resolver: '@nrwl/jest/plugins/resolver',` to jest.config.js like:
```
module.exports = {
  displayName: 'app',
  preset: 'react-native',
  resolver: '@nrwl/jest/plugins/resolver',
  moduleFileExtensions: ['ts', 'js', 'html', 'tsx', 'jsx'],
  setupFilesAfterEnv: ['<rootDir>/test-setup.ts'],
  transform: {
    '\\.(js|ts|tsx)$': require.resolve('react-native/jest/preprocessor.js'),
    '^.+\\.(bmp|gif|jpg|jpeg|mp4|png|psd|svg|webp)$': require.resolve(
      'react-native/jest/assetFileTransformer.js'
    ),
  },
};
```

**Comment by guiccbr** [comment]
Thank you, @xiongemi, that works!

**Comment by guiccbr** [comment]
@xiongemi, the fix that you proposed solved the problem, however I have another one now.

I need to use transformIgnorePatterns on my jest config, but whenever I add it to the configs, I'm getting a "regeneratorRuntime is not defined error" on my tests.

I tried to solve by by installing regenerator-runtime and importing on `test-setup.ts`, but it doesn't have any effect.

This is my jest config:

```
module.exports = {
  displayName: 'my-library',
  preset: 'react-native',
  resolver: '@nrwl/jest/plugins/resolver',
  moduleFileExtensions: ['ts', 'js', 'html', 'tsx', 'jsx'],
  setupFilesAfterEnv: ['<rootDir>/test-setup.ts'],
  transformIgnorePatterns: ['<rootDir>/node_modules/(?!(react-native|victory.*)/)'],
  transform: {
    '\\.(js|ts|tsx)$': require.resolve('react-native/jest/preprocessor.js'),
    '^.+\\.(bmp|gif|jpg|jpeg|mp4|png|psd|svg|webp)$': require.resolve(
      'react-native/jest/assetFileTransformer.js'
    ),
  },
};
```

Do you know how to solve that one?

**Comment by guiccbr** [comment]
For anyone that has the problem from my last comment, the solution here was to remove `<rootDir>` from transformIgnorePatterns, and everything started to work well again.

Thanks!
